version: "3.8"

services:
  app:
    container_name: nestjs-pilot-project
    image: nestjs-api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_EXTERNAL_PORT-3000}:{APP_INTERNAL_PORT-3000}"
      - 9229:9229
    command: npm run stard:debug

    networks:
      - pilot-project-network
    volumes:
      - .:/usr/src/app/
      - .:/usr/src/app/node_modules
    restart: unless-stopped

  db:
    container_name: pg_container
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_EXTERNAL_PORT-54322}:${POSTGRES_INTERNAL_PORT-5432}"
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_INTERNAL_PORT}
    ports:
      - "${PGADMIN_EXTERNAL_PORT-50500}:${PGADMIN_INTERNAL_PORT-5050}"

volumes:
  postgres-data: {}

networks:
  pilot-project-network: