version: "3.7"

services:
  app:
    container_name: nest_users_app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - nest-users
    env_file:
      - .env

  db:
    container_name: postgres_users_db
    image: postgres:latest
    networks:
      - nest-users
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: users_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #     PGADMIN_LISTEN_PORT: ${PGADMIN_INTERNAL_PORT}
  #   ports:
  #     - "${PGADMIN_EXTERNAL_PORT-5050}:${PGADMIN_INTERNAL_PORT-5050}"
  #   networks:
  #     - pilot-project-network
  #   env_file:
  #     - .env

volumes:
  pgdata: {}

networks:
  nest-users: